steps:
    # 1단계 => docker-compose -f docker-compose.prod.yaml build
    - name: docker/compose:1.29.0
      args:
          - -f
          - docker-compose.prod.yaml
          - build

    # 2단계 => docker-compose -f docker-compose.prod.yaml push
    - name: docker/compose:1.29.0
      args:
          - -f
          - docker-compose.prod.yaml
          - push

    # 3단계 => kubectl set image deployment/farmyoubackend farmyou-backend-sha256-1=asia.gcr.io/f7b3team01server/farmyou-backend:0.15
    - name: 'gcr.io/cloud-builders/kubectl'
      args:
          - set
          - image
          - deployment/farmyoubackend
          - farmyou-backend-sha256-1=asia.gcr.io/f7b3team01server/farmyou-backend:0.50
      env:
          - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
          - CLOUDSDK_CONTAINER_CLUSTER=farmyou-cluster-1
