steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        # 'deployment/', 쿠버네티스 클러스터 
        'my-backend-sha256-1=asia.grc.io/f7b3team01server/formyou:0.1',
      ]
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1