version: '3.7'

services:
  my_backend:
    image: asia.gcr.io/f7b3team01server/farmyou-backend:0.2

    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000
