version: '3.7'

services:
    my_backend:
        image: asia.gcr.io/famryouserver/farmyou-backend:0.92
        platform: linux/x86_64
        build:
            context: .
            dockerfile: Dockerfile
        # env_file:
        #   - ./.env.prod
        ports:
            - 3000:3000
